# Generated by Django 5.0.14 on 2026-03-25 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Material Type',
                'verbose_name_plural': 'Material Types',
            },
        ),
        migrations.CreateModel(
            name='RecyclerPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recyclers.materialtype')),
                ('recycler', models.ForeignKey(limit_choices_to={'role': 'RECYCLER'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recycler Purchase',
                'verbose_name_plural': 'Recycler Purchases',
                'ordering': ['-purchase_date'],
                'indexes': [models.Index(fields=['recycler', 'purchase_date'], name='purchase_recycler_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecyclingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recycler', models.ForeignKey(limit_choices_to={'role': 'RECYCLER'}, on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(limit_choices_to={'role': 'RESIDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='recycling_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recycling Certificate',
                'verbose_name_plural': 'Recycling Certificates',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['certificate_number'], name='cert_number_idx'), models.Index(fields=['resident'], name='cert_resident_idx')],
            },
        ),
    ]
