# Generated by Django 5.0.14 on 2026-03-30 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recyclers', '0001_initial'),
        ('wards', '0002_rename_wards_ward_boundar_300e88_gist_wards_ward_boundar_2da4fc_gist'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtype',
            name='category',
            field=models.CharField(blank=True, help_text='e.g., Plastic, Paper, Metal', max_length=50),
        ),
        migrations.AddField(
            model_name='recyclerpurchase',
            name='source_ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycler_purchases', to='wards.ward'),
        ),
        migrations.AddField(
            model_name='recyclingcertificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='recyclingcertificate',
            name='purchases',
            field=models.ManyToManyField(related_name='certificates', to='recyclers.recyclerpurchase'),
        ),
        migrations.AddField(
            model_name='recyclingcertificate',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
