# Generated by Django 5.0.14 on 2026-03-30 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recyclers', '0002_materialtype_category_recyclerpurchase_source_ward_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclingcertificate',
            name='resident',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'RESIDENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recycling_certificates', to=settings.AUTH_USER_MODEL),
        ),
    ]
