# Generated by Django 5.0.14 on 2026-03-30 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recyclers', '0003_alter_recyclingcertificate_resident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialtype',
            old_name='price_per_unit',
            new_name='base_price',
        ),
        migrations.RenameField(
            model_name='recyclerpurchase',
            old_name='total_price',
            new_name='amount_paid',
        ),
        migrations.RenameField(
            model_name='recyclerpurchase',
            old_name='quantity',
            new_name='weight_kg',
        ),
    ]
