# Generated by Django 5.0.14 on 2026-03-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sync Queue Item',
                'verbose_name_plural': 'Sync Queue Items',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['is_synced'], name='sync_pending_idx'), models.Index(fields=['model_name', 'object_id'], name='sync_obj_idx')],
            },
        ),
    ]
