# Generated by Django 5.0.14 on 2026-03-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_syncqueue_device_id_syncqueue_status_syncqueue_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncqueue',
            name='client_id',
            field=models.UUIDField(blank=True, help_text='Unique ID from the mobile app for idempotency', null=True),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='conflict_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syncqueue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('CONFLICT', 'Conflict'), ('ERROR', 'Error')], default='PENDING', max_length=10),
        ),
    ]
