# Generated by Django 5.0.14 on 2026-03-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_syncqueue_client_id_syncqueue_conflict_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncqueue',
            name='client_timestamp',
            field=models.DateTimeField(blank=True, help_text='When the action occurred on the device', null=True),
        ),
    ]
