# Generated by Django 5.0.14 on 2026-03-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
