# Generated by Django 5.0.14 on 2026-03-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ward',
            new_name='wards_ward_boundar_2da4fc_gist',
            old_name='wards_ward_boundar_300e88_gist',
        ),
    ]
