# Generated by Django 5.0.14 on 2026-04-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0002_rename_wards_ward_boundar_300e88_gist_wards_ward_boundar_2da4fc_gist'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='total_households',
            field=models.PositiveIntegerField(default=100, help_text='Total estimated households in this ward for coverage metrics'),
        ),
    ]
