# Generated by Django 5.0.14 on 2026-03-25 09:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='GPS location of the complaint', null=True, srid=4326),
        ),
    ]
