# Generated by Django 5.0.14 on 2026-03-26 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='complaint',
            name='complaint_resident_idx',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='resident',
        ),
        migrations.AddField(
            model_name='complaint',
            name='reporter',
            field=models.ForeignKey(default=1, limit_choices_to={'role__in': ['RESIDENT', 'HKS_WORKER']}, on_delete=django.db.models.deletion.CASCADE, related_name='reported_complaints', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('PICKUP', 'Missed Pickup'), ('CLEANLINESS', 'Lack of Cleanliness'), ('BEHAVIOR', 'Staff Behavior'), ('PAYMENT', 'Payment Issue'), ('OVERFLOW', 'Overflowing Bins'), ('BLOCKED', 'Access Blocked'), ('UNAVAILABLE', 'Resident Unavailable'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['reporter'], name='complaint_reporter_idx'),
        ),
    ]
