# Generated by Django 5.0.14 on 2026-03-25 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('verification_image', models.ImageField(blank=True, null=True, upload_to='pickups/verifications/')),
                ('comments', models.TextField(blank=True)),
                ('pickup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='pickups.pickup')),
                ('verified_by', models.ForeignKey(limit_choices_to={'role': 'HKS_WORKER'}, on_delete=django.db.models.deletion.CASCADE, related_name='verified_pickups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pickup Verification',
                'verbose_name_plural': 'Pickup Verifications',
            },
        ),
    ]
