# Generated by Django 5.0.14 on 2026-03-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0002_pickupverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated weight of waste collected', max_digits=10, null=True),
        ),
    ]
