# Generated by Django 5.0.14 on 2026-03-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0003_pickup_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='time_slot',
            field=models.CharField(blank=True, help_text="e.g., '10:00-12:00'", max_length=50, null=True),
        ),
    ]
