# Generated by Django 5.0.14 on 2026-03-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0004_pickup_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='notes',
            field=models.TextField(blank=True, help_text='Mandatory note if GPS override was used'),
        ),
        migrations.AddField(
            model_name='pickupverification',
            name='ai_classification',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pickupverification',
            name='contamination_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickupverification',
            name='distance_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickupverification',
            name='is_gps_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickupverification',
            name='requires_admin_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickupverification',
            name='waste_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
