# Generated by Django 5.0.14 on 2026-03-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0005_pickup_notes_pickupverification_ai_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='waste_type',
            field=models.CharField(choices=[('dry', 'Dry Waste'), ('wet', 'Wet Waste'), ('hazardous', 'Hazardous Waste'), ('e-waste', 'E-Waste'), ('biomedical', 'Biomedical Waste')], max_length=20),
        ),
    ]
