# Generated by Django 5.0.14 on 2026-03-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0006_alter_pickup_waste_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='Generated QR code image for verification', null=True, upload_to='pickups/qrcodes/'),
        ),
    ]
