# Generated by Django 5.0.14 on 2026-03-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0007_pickup_qr_code_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupverification',
            name='contamination_flag',
            field=models.BooleanField(default=False),
        ),
    ]
