# Generated by Django 5.0.14 on 2026-03-30 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0008_pickupverification_contamination_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_range', models.CharField(help_text="e.g. '08:00 - 10:00'", max_length=50)),
                ('label', models.CharField(help_text="e.g. 'Morning Shift'", max_length=100)),
                ('capacity', models.PositiveIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['time_range'],
            },
        ),
        migrations.AlterField(
            model_name='pickup',
            name='time_slot',
            field=models.CharField(blank=True, help_text="e.g., '10:00-12:00' (Legacy or Custom)", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pickup',
            name='time_slot_ref',
            field=models.ForeignKey(blank=True, help_text='Reference to the master slot configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to='pickups.pickupslot'),
        ),
    ]
