# Generated by Django 5.0.14 on 2026-04-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0009_pickupslot_alter_pickup_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupslot',
            name='capacity',
            field=models.PositiveIntegerField(default=15, help_text='Max pickups allowed in this slot'),
        ),
        migrations.AlterField(
            model_name='pickupslot',
            name='label',
            field=models.CharField(default='Time Slot', help_text="e.g. 'Morning Shift'", max_length=100),
        ),
        migrations.AlterField(
            model_name='pickupslot',
            name='time_range',
            field=models.CharField(default='00:00 - 00:00', help_text="e.g. '08:00 - 10:00'", max_length=50),
        ),
    ]
