# Generated by Django 5.0.14 on 2026-04-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0010_alter_pickupslot_capacity_alter_pickupslot_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='is_instant',
            field=models.BooleanField(default=False, help_text='If true, this pickup was requested on-demand outside of a slot.'),
        ),
    ]
