# Generated by Django 5.0.14 on 2026-03-25 08:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI / Digital'), ('BANK_TRANSFER', 'Bank Transfer')], default='CASH', max_length=20)),
                ('receipt_number', models.CharField(db_index=True, max_length=25, unique=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(limit_choices_to={'role': 'HKS_WORKER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections_made', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(limit_choices_to={'role': 'RESIDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='fee_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fee Collection',
                'verbose_name_plural': 'Fee Collections',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['receipt_number'], name='fee_receipt_idx'), models.Index(fields=['resident', 'payment_date'], name='fee_res_date_idx')],
            },
        ),
    ]
