# Generated by Django 5.0.14 on 2026-03-25 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('wards', '0002_rename_wards_ward_boundar_300e88_gist_wards_ward_boundar_2da4fc_gist'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollection',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_collections', to='wards.ward'),
        ),
    ]
