# Generated by Django 5.0.14 on 2026-03-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pickups/review_images/')),
                ('ai_classification', models.CharField(choices=[('clean', 'Clean'), ('contaminated', 'Contaminated'), ('mixed', 'Mixed')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('contamination_flag', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=False)),
                ('points_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
