# Generated by Django 5.0.14 on 2026-03-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_reward_pickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('points_cost', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reward Item',
                'verbose_name_plural': 'Reward Items',
                'ordering': ['points_cost'],
            },
        ),
        migrations.AddField(
            model_name='reward',
            name='running_balance',
            field=models.IntegerField(default=0, help_text='Total balance after this transaction'),
        ),
    ]
