# Generated by Django 5.0.14 on 2026-03-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_rewarditem_reward_running_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_pickup_points', models.PositiveIntegerField(default=10)),
                ('contaminated_pickup_points', models.PositiveIntegerField(default=5)),
                ('streak_bonus_points', models.PositiveIntegerField(default=50)),
                ('streak_threshold_weeks', models.PositiveIntegerField(default=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reward Settings',
                'verbose_name_plural': 'Reward Settings',
            },
        ),
    ]
