# Generated by Django 5.0.14 on 2026-03-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='ppe_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/ppe/'),
        ),
    ]
