# Generated by Django 5.0.14 on 2026-03-25 09:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancelog_ppe_selfie'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='check_in_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='GPS location at check-in', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='has_boots',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='has_gloves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='has_mask',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='has_vest',
            field=models.BooleanField(default=False),
        ),
    ]
