# Generated by Django 5.0.14 on 2026-03-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancelog_check_in_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='ppe_photo_url',
            field=models.URLField(blank=True, help_text='Verifiable remote URL for PPE selfie', max_length=500, null=True),
        ),
    ]
