# Generated by Django 5.0.14 on 2026-03-28 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NPSSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='NPS score from 0 to 10')),
                ('comment', models.TextField(blank=True, help_text='Optional qualitative feedback')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('next_prompt_at', models.DateTimeField(help_text='Earliest date the survey can be shown again')),
                ('resident', models.OneToOneField(limit_choices_to={'role': 'RESIDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='nps_survey', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NPS Survey Response',
                'verbose_name_plural': 'NPS Survey Responses',
                'indexes': [models.Index(fields=['submitted_at'], name='nps_submitted_at_idx')],
            },
        ),
    ]
