# Generated by Django 5.0.14 on 2026-03-30 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_nps_survey'),
        ('wards', '0002_rename_wards_ward_boundar_300e88_gist_wards_ward_boundar_2da4fc_gist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WardCollectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdfs/')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='reports/csvs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_reports', to='wards.ward')),
            ],
            options={
                'verbose_name': 'Ward Collection Report',
                'verbose_name_plural': 'Ward Collection Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
