# Generated by Django 5.0.14 on 2026-04-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_wardcollectionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardcollectionreport',
            name='report_type',
            field=models.CharField(choices=[('WARD', 'Ward Report'), ('COMPLIANCE', 'Suchitwa Mission Compliance'), ('PERFORMANCE', 'Worker Performance'), ('FINANCIAL', 'Fee Collection Summary')], default='WARD', max_length=20),
        ),
    ]
